import time
import asyncio
from fastapi import Request
from starlette.responses import Response
from core.logging import request_logger
from database.mongo import db

async def log_request(request: Request, call_next) -> Response:
    """
    Middleware to log details of incoming HTTP requests.

    This middleware measures the processing time of each request and logs
    various details (timestamp, method, path, IP address, user agent, process time,
    and status code) using the request_logger. Additionally, it attempts to store
    these logs in MongoDB by offloading the blocking insert operation to a separate thread.
    Args:
        request (Request): The incoming HTTP request.
        call_next: A callable that takes the request and returns a Response.
    Returns:
        Response: The HTTP response generated by downstream middleware or the endpoint.
    """
    # Record the start time of the request.
    start_time = time.time()
    
    # Process the request through the next middleware/route handler.
    response = await call_next(request)
    
    # Calculate the total processing time.
    process_time = time.time() - start_time

    # Prepare the log data.
    log_data = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),
        "method": request.method,
        "path": request.url.path,
        "ip_address": request.client.host,
        "user_agent": request.headers.get("user-agent"),
        "process_time": f"{process_time:.4f}s",
        "status_code": response.status_code,
    }

    # Log the request data to the designated request logger.
    request_logger.info(log_data)

    try:
        # Offload the blocking MongoDB insert operation to a thread to avoid blocking the event loop.
        await asyncio.to_thread(db.get_collection("request_logs").insert_one, log_data)
    except Exception as e:
        request_logger.error({"error": f"Failed to store request log: {e}"}, exc_info=True)

    return response